version: "3.9"

services:
  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./web:/app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
